import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    width: width,
    paddingLeft: 26,
    paddingRight: 26,
    paddingTop: 40,
    paddingBottom: 40,
  },
  calculateShippingContainer: {
    width: width * 0.9,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 19,
    paddingBottom: 19,
    backgroundColor: "#DEF5DA",
    borderRadius: 8,
    marginTop: 10,
    flexDirection: "row",
  },
  calculateShippingIcon: {
    width: 62,
    height: 33,
    marginRight: 16,
  },
  calculateShippingText: {
    fontFamily: "Satoshi",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 12,
    color: "#4D4D4D",
    lineHeight: 16,
    flex: 1,
    flexWrap: "wrap",
  },
  descriptionContainer: {
    width: width,
    paddingLeft: 35,
    paddingRight: 35,
    paddingTop: 10,
    paddingBottom: 35,
    backgroundColor: "#DEF5DA",
    flex: 1,
  },
  image: {
    height: 362,
    flex: 1,
    borderRadius: 8,
  },
  imageGallery: {
    width: width,
    flexDirection: "row",
    paddingTop: 10,
  },
  imageGalleryItem: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 16,
  },
  partnerName: {
    fontFamily: "Satoshi",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 11,
    color: "#4D4D4D",
    textDecorationLine: "underline",
    marginRight: 10,
  },
  verified: {
    width: 20,
    height: 20,
  },
  title: {
    fontFamily: "Satoshi",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 21,
    paddingBottom: 5,
    color: "#4D4D4D",
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
  },
  price: {
    fontFamily: "Satoshi",
    fontStyle: "normal",
    fontWeight: "900",
    fontSize: 21,
    color: "#55D187",
  },
  oldPrice: {
    fontFamily: "Satoshi",
    fontStyle: "normal",
    fontWeight: "900",
    fontSize: 16,
    color: "#4D4D4D",
    textDecorationLine: "line-through",
    marginLeft: 15,
  },
  button: {
    width: width * 0.9,
    height: 62,
    backgroundColor: "#55D187",
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  buttonText: {
    fontFamily: "Satoshi",
    fontStyle: "normal",
    fontWeight: "900",
    fontSize: 21.5,
    color: "#F7FDF9",
  },
  wave: {
    width: width,
    height: 38.5,
  },
  collapsingContainer: {
    width: width * 0.9,
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    paddingTop: 11.5,
    paddingBottom: 11.5,
  },
  collapsingContainerIcon: {
    width: 12,
    height: 6,
    flex: 1,
  },
  descriptionTitle: {
    fontFamily: "Satoshi",
    fontStyle: "normal",
    fontWeight: "900",
    fontSize: 17,
    color: "#4D4D4D",
  },
  descriptionText: {
    fontFamily: "Satoshi",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 14,
    color: "#4D4D4D",
  },
  cardView: {
    backgroundColor: "#fff",
    flex: 1,
    borderRadius: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0.5, height: 0.5 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
    padding: 30,
    marginTop: 38,
  },
  sellerDetails: {
    fontFamily: "Satoshi",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 12,
    color: "#4D4D4D",
    lineHeight: 22,
  },
  sellerImage: {
    width: 81,
    height: 81,
    borderRadius: 60,
  },
});

export default styles;
